import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');
  
  // Clear existing data to prevent unique constraint failures
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.review.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.productSpec.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.address.deleteMany();
  await prisma.user.deleteMany();

  const categoryMap = {};
  categoryMap['Electronics'] = await prisma.category.create({ data: { name: 'Electronics', slug: 'electronics' } });
  categoryMap['Grocery'] = await prisma.category.create({ data: { name: 'Grocery', slug: 'grocery' } });
  categoryMap['Books'] = await prisma.category.create({ data: { name: 'Books', slug: 'books' } });
  categoryMap['Fashion'] = await prisma.category.create({ data: { name: 'Fashion', slug: 'fashion' } });
  categoryMap['Home & Kitchen'] = await prisma.category.create({ data: { name: 'Home & Kitchen', slug: 'home-kitchen' } });
  categoryMap['Sports'] = await prisma.category.create({ data: { name: 'Sports', slug: 'sports' } });
  categoryMap['Beauty'] = await prisma.category.create({ data: { name: 'Beauty', slug: 'beauty' } });
  categoryMap['Toys'] = await prisma.category.create({ data: { name: 'Toys', slug: 'toys' } });

  const products = [
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Sony WH-1000XM5 Wireless Headphones`,
      brand: `Sony`,
      slug: 'sony-wh-1000xm5-wireless-headphones-002fns',
      description: `Enjoy this high-quality Sony WH-1000XM5 Wireless Headphones from Sony. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 399.99,
      price: 348,
      stock: 98,
      rating: 4.4,
      reviewCount: 23,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Apple MacBook Air M2`,
      brand: `Apple`,
      slug: 'apple-macbook-air-m2-9uox9',
      description: `Enjoy this high-quality Apple MacBook Air M2 from Apple. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 1199,
      price: 1099,
      stock: 83,
      rating: 4.2,
      reviewCount: 318,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Samsung Galaxy S23 Ultra`,
      brand: `Samsung`,
      slug: 'samsung-galaxy-s23-ultra-724psf',
      description: `Enjoy this high-quality Samsung Galaxy S23 Ultra from Samsung. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 1199,
      price: 999,
      stock: 89,
      rating: 4.6,
      reviewCount: 371,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `iPad Pro 12.9-inch`,
      brand: `Apple`,
      slug: 'ipad-pro-12-9-inch-ms3qk',
      description: `Enjoy this high-quality iPad Pro 12.9-inch from Apple. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 1099,
      price: 1049,
      stock: 63,
      rating: 4.2,
      reviewCount: 55,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Nintendo Switch OLED`,
      brand: `Nintendo`,
      slug: 'nintendo-switch-oled-z1w65',
      description: `Enjoy this high-quality Nintendo Switch OLED from Nintendo. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 349,
      price: 349,
      stock: 43,
      rating: 4.9,
      reviewCount: 465,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61kjXatIUqL._SX522_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Dell XPS 13 Laptop`,
      brand: `Dell`,
      slug: 'dell-xps-13-laptop-tae91a',
      description: `Enjoy this high-quality Dell XPS 13 Laptop from Dell. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 1499,
      price: 1299,
      stock: 74,
      rating: 4.2,
      reviewCount: 235,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `GoPro HERO11 Black`,
      brand: `GoPro`,
      slug: 'gopro-hero11-black-y9m4es',
      description: `Enjoy this high-quality GoPro HERO11 Black from GoPro. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 499,
      price: 399,
      stock: 19,
      rating: 4.6,
      reviewCount: 419,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61tY8Vx6GSL._AC_SY879_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Bose QuietComfort Earbuds II`,
      brand: `Bose`,
      slug: 'bose-quietcomfort-earbuds-ii-olc75',
      description: `Enjoy this high-quality Bose QuietComfort Earbuds II from Bose. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 299,
      price: 249,
      stock: 57,
      rating: 4.1,
      reviewCount: 235,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `LG C2 55-Inch OLED TV`,
      brand: `LG`,
      slug: 'lg-c2-55-inch-oled-tv-ay1qwj',
      description: `Enjoy this high-quality LG C2 55-Inch OLED TV from LG. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 1499,
      price: 1296,
      stock: 66,
      rating: 4.3,
      reviewCount: 121,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Electronics'].id,
      name: `Logitech MX Master 3S Mouse`,
      brand: `Logitech`,
      slug: 'logitech-mx-master-3s-mouse-f59jp',
      description: `Enjoy this high-quality Logitech MX Master 3S Mouse from Logitech. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 99,
      price: 99,
      stock: 41,
      rating: 4.4,
      reviewCount: 418,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Organic Honey 500g`,
      brand: `Nature Farms`,
      slug: 'organic-honey-500g-9jtkgi',
      description: `Enjoy this high-quality Organic Honey 500g from Nature Farms. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 15.99,
      price: 12.99,
      stock: 22,
      rating: 4.4,
      reviewCount: 264,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/7124ixWZHpL._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Premium Arabica Coffee Beans 1kg`,
      brand: `RoastMasters`,
      slug: 'premium-arabica-coffee-beans-1kg-ed42ca',
      description: `Enjoy this high-quality Premium Arabica Coffee Beans 1kg from RoastMasters. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 29.99,
      price: 24.5,
      stock: 106,
      rating: 4.4,
      reviewCount: 88,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Extra Virgin Olive Oil 1L`,
      brand: `Tuscan Sun`,
      slug: 'extra-virgin-olive-oil-1l-gfhwqr',
      description: `Enjoy this high-quality Extra Virgin Olive Oil 1L from Tuscan Sun. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 22.99,
      price: 18.99,
      stock: 35,
      rating: 5.0,
      reviewCount: 231,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81loucHrZNL._SX679_PIbundle-2,TopRight,0,0_AA679SH20_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Almond Butter 16oz`,
      brand: `Nutty`,
      slug: 'almond-butter-16oz-gqsw6o',
      description: `Enjoy this high-quality Almond Butter 16oz from Nutty. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 11.99,
      price: 8.99,
      stock: 33,
      rating: 4.8,
      reviewCount: 471,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71rK6Ig+o1L._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Organic Quinoa 2lbs`,
      brand: `HealthyGrains`,
      slug: 'organic-quinoa-2lbs-h2tym',
      description: `Enjoy this high-quality Organic Quinoa 2lbs from HealthyGrains. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 12.99,
      price: 9.99,
      stock: 37,
      rating: 4.0,
      reviewCount: 114,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Himalayan Pink Salt 1lb`,
      brand: `SpiceWorld`,
      slug: 'himalayan-pink-salt-1lb-y8pph',
      description: `Enjoy this high-quality Himalayan Pink Salt 1lb from SpiceWorld. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 7.99,
      price: 5.49,
      stock: 43,
      rating: 4.8,
      reviewCount: 53,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61lmyI99e1L._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Maple Syrup Grade A 32oz`,
      brand: `VermontFarms`,
      slug: 'maple-syrup-grade-a-32oz-f25k6',
      description: `Enjoy this high-quality Maple Syrup Grade A 32oz from VermontFarms. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 26.99,
      price: 21.99,
      stock: 75,
      rating: 4.5,
      reviewCount: 128,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/716sPT2WADL._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Rolled Oats 5lbs`,
      brand: `FarmFresh`,
      slug: 'rolled-oats-5lbs-oq8n4o',
      description: `Enjoy this high-quality Rolled Oats 5lbs from FarmFresh. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 14.99,
      price: 11.5,
      stock: 26,
      rating: 4.3,
      reviewCount: 52,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Green Tea Bags 100ct`,
      brand: `TeaTime`,
      slug: 'green-tea-bags-100ct-5m7ry',
      description: `Enjoy this high-quality Green Tea Bags 100ct from TeaTime. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 18,
      price: 14.25,
      stock: 105,
      rating: 4.7,
      reviewCount: 212,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Grocery'].id,
      name: `Dried Mango Slices 16oz`,
      brand: `TropicalSnacks`,
      slug: 'dried-mango-slices-16oz-9ml60f',
      description: `Enjoy this high-quality Dried Mango Slices 16oz from TropicalSnacks. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 20.99,
      price: 16.99,
      stock: 29,
      rating: 4.3,
      reviewCount: 80,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `The Midnight Library`,
      brand: `Penguin`,
      slug: 'the-midnight-library-dcq1se',
      description: `Enjoy this high-quality The Midnight Library from Penguin. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 26,
      price: 18.5,
      stock: 32,
      rating: 4.9,
      reviewCount: 174,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `Atomic Habits`,
      brand: `Avery`,
      slug: 'atomic-habits-ybtfhc',
      description: `Enjoy this high-quality Atomic Habits from Avery. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 27,
      price: 16.99,
      stock: 46,
      rating: 4.7,
      reviewCount: 144,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `Sapiens: A Brief History of Humankind`,
      brand: `Harper`,
      slug: 'sapiens-a-brief-history-of-humankind-gwzqv4',
      description: `Enjoy this high-quality Sapiens: A Brief History of Humankind from Harper. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 24.99,
      price: 14.99,
      stock: 109,
      rating: 4.6,
      reviewCount: 88,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `Dune`,
      brand: `Ace`,
      slug: 'dune-zksr6i',
      description: `Enjoy this high-quality Dune from Ace. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 18,
      price: 10.99,
      stock: 45,
      rating: 4.2,
      reviewCount: 178,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81Ua99CURsL._SY522_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `Thinking, Fast and Slow`,
      brand: `FSG`,
      slug: 'thinking-fast-and-slow-h8dtw',
      description: `Enjoy this high-quality Thinking, Fast and Slow from FSG. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 20,
      price: 13.5,
      stock: 50,
      rating: 4.0,
      reviewCount: 190,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `Educated: A Memoir`,
      brand: `Random House`,
      slug: 'educated-a-memoir-ezmiu',
      description: `Enjoy this high-quality Educated: A Memoir from Random House. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 28,
      price: 15,
      stock: 35,
      rating: 4.8,
      reviewCount: 362,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `1984`,
      brand: `Signet`,
      slug: '1984-9bckep',
      description: `Enjoy this high-quality 1984 from Signet. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 12.99,
      price: 9.99,
      stock: 35,
      rating: 4.0,
      reviewCount: 480,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `The Great Gatsby`,
      brand: `Scribner`,
      slug: 'the-great-gatsby-8wiwq',
      description: `Enjoy this high-quality The Great Gatsby from Scribner. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 11.99,
      price: 8.99,
      stock: 41,
      rating: 4.1,
      reviewCount: 15,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81T4dS6IkaL._SY522_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `To Kill a Mockingbird`,
      brand: `Harper`,
      slug: 'to-kill-a-mockingbird-6oyou',
      description: `Enjoy this high-quality To Kill a Mockingbird from Harper. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 16.99,
      price: 11.5,
      stock: 73,
      rating: 4.0,
      reviewCount: 121,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81O7u0dGaWL._SY522_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Books'].id,
      name: `The Alchemist`,
      brand: `HarperOne`,
      slug: 'the-alchemist-7gsry9',
      description: `Enjoy this high-quality The Alchemist from HarperOne. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 17.99,
      price: 12.99,
      stock: 97,
      rating: 4.5,
      reviewCount: 201,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Classic Denim Jacket`,
      brand: `Levi's`,
      slug: 'classic-denim-jacket-oukbfkj',
      description: `Enjoy this high-quality Classic Denim Jacket from Levi's. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 120,
      price: 89.5,
      stock: 58,
      rating: 4.2,
      reviewCount: 409,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/714oebh-u2L._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Minimalist Canvas Sneakers`,
      brand: `Generic`,
      slug: 'minimalist-canvas-sneakers-kq8aeu',
      description: `Enjoy this high-quality Minimalist Canvas Sneakers from Generic. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 69.99,
      price: 49.99,
      stock: 17,
      rating: 4.2,
      reviewCount: 445,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Men's Oxford Button-Down Shirt`,
      brand: `Brooks Brothers`,
      slug: 'men-s-oxford-button-down-shirt-lccpur',
      description: `Enjoy this high-quality Men's Oxford Button-Down Shirt from Brooks Brothers. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 85,
      price: 65,
      stock: 74,
      rating: 4.3,
      reviewCount: 114,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71LUJgXAGxL._AC_SY879_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Women's Leather Tote Bag`,
      brand: `Coach`,
      slug: 'women-s-leather-tote-bag-f5s4bs',
      description: `Enjoy this high-quality Women's Leather Tote Bag from Coach. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 250,
      price: 195,
      stock: 41,
      rating: 4.4,
      reviewCount: 508,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Polarized Aviator Sunglasses`,
      brand: `Ray-Ban`,
      slug: 'polarized-aviator-sunglasses-1ywxwj',
      description: `Enjoy this high-quality Polarized Aviator Sunglasses from Ray-Ban. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 178,
      price: 154,
      stock: 103,
      rating: 4.1,
      reviewCount: 506,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Slim Fit Chino Pants`,
      brand: `Dockers`,
      slug: 'slim-fit-chino-pants-j0jpkm',
      description: `Enjoy this high-quality Slim Fit Chino Pants from Dockers. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 65,
      price: 45,
      stock: 31,
      rating: 4.8,
      reviewCount: 422,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Women's Running Shoes`,
      brand: `Nike`,
      slug: 'women-s-running-shoes-3rwfwb',
      description: `Enjoy this high-quality Women's Running Shoes from Nike. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 140,
      price: 120,
      stock: 48,
      rating: 4.3,
      reviewCount: 48,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Cashmere V-Neck Sweater`,
      brand: `Everlane`,
      slug: 'cashmere-v-neck-sweater-0jt5cc',
      description: `Enjoy this high-quality Cashmere V-Neck Sweater from Everlane. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 160,
      price: 135,
      stock: 78,
      rating: 4.9,
      reviewCount: 502,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Stainless Steel Chronograph Watch`,
      brand: `Fossil`,
      slug: 'stainless-steel-chronograph-watch-j3npig9',
      description: `Enjoy this high-quality Stainless Steel Chronograph Watch from Fossil. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 165,
      price: 125,
      stock: 94,
      rating: 4.0,
      reviewCount: 355,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Fashion'].id,
      name: `Pleated Midi Skirt`,
      brand: `Zara`,
      slug: 'pleated-midi-skirt-ongbao',
      description: `Enjoy this high-quality Pleated Midi Skirt from Zara. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 49.9,
      price: 39.9,
      stock: 66,
      rating: 4.6,
      reviewCount: 86,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Ceramic Pour-Over Coffee Maker`,
      brand: `HomeGoods`,
      slug: 'ceramic-pour-over-coffee-maker-xi37ql',
      description: `Enjoy this high-quality Ceramic Pour-Over Coffee Maker from HomeGoods. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 35,
      price: 24.99,
      stock: 107,
      rating: 4.3,
      reviewCount: 102,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61-crgly-8L._AC_SY879_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Linen Duvet Cover Set`,
      brand: `ComfortHome`,
      slug: 'linen-duvet-cover-set-hcb4cp',
      description: `Enjoy this high-quality Linen Duvet Cover Set from ComfortHome. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 249,
      price: 189,
      stock: 70,
      rating: 4.9,
      reviewCount: 158,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Non-Stick Cookware Set 10-Piece`,
      brand: `T-fal`,
      slug: 'non-stick-cookware-set-10-piece-6570ca',
      description: `Enjoy this high-quality Non-Stick Cookware Set 10-Piece from T-fal. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 149.99,
      price: 99.99,
      stock: 101,
      rating: 4.3,
      reviewCount: 49,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81jZNuVLr7L._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Robot Vacuum Cleaner`,
      brand: `iRobot`,
      slug: 'robot-vacuum-cleaner-fap4y0p',
      description: `Enjoy this high-quality Robot Vacuum Cleaner from iRobot. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 399,
      price: 299,
      stock: 82,
      rating: 4.2,
      reviewCount: 124,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1589923158776-cb4485d99fd6?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Memory Foam Mattress Topper`,
      brand: `Sleepwell`,
      slug: 'memory-foam-mattress-topper-ysz4ws',
      description: `Enjoy this high-quality Memory Foam Mattress Topper from Sleepwell. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 120,
      price: 79.99,
      stock: 100,
      rating: 4.3,
      reviewCount: 503,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Set of 4 Wine Glasses`,
      brand: `Riedel`,
      slug: 'set-of-4-wine-glasses-pzda8k',
      description: `Enjoy this high-quality Set of 4 Wine Glasses from Riedel. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 60,
      price: 45,
      stock: 96,
      rating: 5.0,
      reviewCount: 74,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61tYwvWR9+L._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Electric Kettle 1.7L`,
      brand: `Breville`,
      slug: 'electric-kettle-1-7l-d3dr7',
      description: `Enjoy this high-quality Electric Kettle 1.7L from Breville. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 80,
      price: 59.95,
      stock: 105,
      rating: 4.9,
      reviewCount: 15,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71EfmuBo3gL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Cast Iron Skillet 12-Inch`,
      brand: `Lodge`,
      slug: 'cast-iron-skillet-12-inch-ctq0t',
      description: `Enjoy this high-quality Cast Iron Skillet 12-Inch from Lodge. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 45,
      price: 29.9,
      stock: 65,
      rating: 4.1,
      reviewCount: 361,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71CvJCoQWrL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Bamboo Cutting Board`,
      brand: `GreenerChef`,
      slug: 'bamboo-cutting-board-d6cb69',
      description: `Enjoy this high-quality Bamboo Cutting Board from GreenerChef. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 25,
      price: 19.99,
      stock: 31,
      rating: 4.5,
      reviewCount: 460,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81BJf71smLL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Home & Kitchen'].id,
      name: `Air Purifier for Allergies`,
      brand: `Levoit`,
      slug: 'air-purifier-for-allergies-8g5m',
      description: `Enjoy this high-quality Air Purifier for Allergies from Levoit. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 119.99,
      price: 89.99,
      stock: 93,
      rating: 4.2,
      reviewCount: 17,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Premium Yoga Mat`,
      brand: `ZenFit`,
      slug: 'premium-yoga-mat-sj43p',
      description: `Enjoy this high-quality Premium Yoga Mat from ZenFit. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 45,
      price: 32.5,
      stock: 98,
      rating: 4.5,
      reviewCount: 68,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Adjustable Dumbbell Set`,
      brand: `PowerLift`,
      slug: 'adjustable-dumbbell-set-gopk9m',
      description: `Enjoy this high-quality Adjustable Dumbbell Set from PowerLift. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 399,
      price: 349,
      stock: 25,
      rating: 4.5,
      reviewCount: 182,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Resistance Bands Set`,
      brand: `FitActive`,
      slug: 'resistance-bands-set-cvw7xd',
      description: `Enjoy this high-quality Resistance Bands Set from FitActive. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 35,
      price: 24.99,
      stock: 61,
      rating: 4.6,
      reviewCount: 32,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1598266663439-2056e6900339?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Foam Roller for Muscle Massage`,
      brand: `TriggerPoint`,
      slug: 'foam-roller-for-muscle-massage-f1doxi',
      description: `Enjoy this high-quality Foam Roller for Muscle Massage from TriggerPoint. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 45,
      price: 34.99,
      stock: 88,
      rating: 4.9,
      reviewCount: 502,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81sC1hrQBsL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Tennis Racket Pro Staff`,
      brand: `Wilson`,
      slug: 'tennis-racket-pro-staff-iph06c',
      description: `Enjoy this high-quality Tennis Racket Pro Staff from Wilson. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 249,
      price: 199,
      stock: 10,
      rating: 4.1,
      reviewCount: 286,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Basketball Official Size`,
      brand: `Spalding`,
      slug: 'basketball-official-size-vcg2dr',
      description: `Enjoy this high-quality Basketball Official Size from Spalding. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 55,
      price: 39.95,
      stock: 57,
      rating: 4.8,
      reviewCount: 350,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Camping Tent 4-Person`,
      brand: `Coleman`,
      slug: 'camping-tent-4-person-bv6gg',
      description: `Enjoy this high-quality Camping Tent 4-Person from Coleman. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 180,
      price: 129.99,
      stock: 101,
      rating: 4.6,
      reviewCount: 243,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61b3VeJSMFL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Cycling Helmet Aerodynamic`,
      brand: `Giro`,
      slug: 'cycling-helmet-aerodynamic-c45mv8',
      description: `Enjoy this high-quality Cycling Helmet Aerodynamic from Giro. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 110,
      price: 85,
      stock: 64,
      rating: 4.7,
      reviewCount: 140,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/51QdW8fJc0L._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Stainless Steel Water Bottle 32oz`,
      brand: `Hydro Flask`,
      slug: 'stainless-steel-water-bottle-32oz-52r9gu',
      description: `Enjoy this high-quality Stainless Steel Water Bottle 32oz from Hydro Flask. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 55,
      price: 44.95,
      stock: 94,
      rating: 4.2,
      reviewCount: 158,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Sports'].id,
      name: `Jump Rope with Counter`,
      brand: `Crossrope`,
      slug: 'jump-rope-with-counter-zlt1zg',
      description: `Enjoy this high-quality Jump Rope with Counter from Crossrope. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 25,
      price: 18.5,
      stock: 39,
      rating: 4.2,
      reviewCount: 205,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61yQzrV3SVL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Vitamin C Serum`,
      brand: `GlowSkin`,
      slug: 'vitamin-c-serum-5th6y',
      description: `Enjoy this high-quality Vitamin C Serum from GlowSkin. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 35,
      price: 28,
      stock: 69,
      rating: 4.1,
      reviewCount: 80,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61U+PCANeOL._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Hydrating Face Moisturizer`,
      brand: `GlowSkin`,
      slug: 'hydrating-face-moisturizer-pptzw',
      description: `Enjoy this high-quality Hydrating Face Moisturizer from GlowSkin. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 24,
      price: 19.5,
      stock: 69,
      rating: 4.0,
      reviewCount: 151,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Matte Liquid Lipstick`,
      brand: `MAC`,
      slug: 'matte-liquid-lipstick-7rzibs',
      description: `Enjoy this high-quality Matte Liquid Lipstick from MAC. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 26,
      price: 22,
      stock: 33,
      rating: 4.3,
      reviewCount: 417,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Eyeshadow Palette 18 Colors`,
      brand: `Urban Decay`,
      slug: 'eyeshadow-palette-18-colors-7j22m',
      description: `Enjoy this high-quality Eyeshadow Palette 18 Colors from Urban Decay. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 54,
      price: 45,
      stock: 22,
      rating: 4.1,
      reviewCount: 154,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81gM3HUH51L._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Volumizing Mascara`,
      brand: `Maybelline`,
      slug: 'volumizing-mascara-k2kuz',
      description: `Enjoy this high-quality Volumizing Mascara from Maybelline. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 12.99,
      price: 9.99,
      stock: 35,
      rating: 4.0,
      reviewCount: 124,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/615weN41jHL._SX522_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Rosewater Facial Toner`,
      brand: `Thayers`,
      slug: 'rosewater-facial-toner-8e47o',
      description: `Enjoy this high-quality Rosewater Facial Toner from Thayers. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 14,
      price: 10.5,
      stock: 76,
      rating: 4.6,
      reviewCount: 142,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61eXQt9+L0L._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Argan Oil Hair Treatment`,
      brand: `Moroccanoil`,
      slug: 'argan-oil-hair-treatment-2rz6nu',
      description: `Enjoy this high-quality Argan Oil Hair Treatment from Moroccanoil. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 42,
      price: 34,
      stock: 59,
      rating: 4.4,
      reviewCount: 371,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `SPF 50 Sunscreen Lotion`,
      brand: `Neutrogena`,
      slug: 'spf-50-sunscreen-lotion-9dqf',
      description: `Enjoy this high-quality SPF 50 Sunscreen Lotion from Neutrogena. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 16.99,
      price: 12.99,
      stock: 36,
      rating: 4.5,
      reviewCount: 398,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71XyYn0Zv7L._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Charcoal Clay Mask`,
      brand: `Origins`,
      slug: 'charcoal-clay-mask-eh4qwp',
      description: `Enjoy this high-quality Charcoal Clay Mask from Origins. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 32,
      price: 27,
      stock: 38,
      rating: 4.8,
      reviewCount: 473,
      images: { create: [{ url: 'https://mughais.com/wp-content/uploads/2024/07/Charcoal-clay-Mask.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Beauty'].id,
      name: `Exfoliating Body Scrub`,
      brand: `Frank Body`,
      slug: 'exfoliating-body-scrub-t12q3e',
      description: `Enjoy this high-quality Exfoliating Body Scrub from Frank Body. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 22,
      price: 18.95,
      stock: 21,
      rating: 4.2,
      reviewCount: 374,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/511VdTzAucL._SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Building Blocks Set (500 pcs)`,
      brand: `CreativeKids`,
      slug: 'building-blocks-set-500-pcs--y9biv',
      description: `Enjoy this high-quality Building Blocks Set (500 pcs) from CreativeKids. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 49.99,
      price: 39.99,
      stock: 13,
      rating: 4.7,
      reviewCount: 464,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Remote Control Car`,
      brand: `SpeedRacer`,
      slug: 'remote-control-car-olbbvz',
      description: `Enjoy this high-quality Remote Control Car from SpeedRacer. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 59.99,
      price: 45,
      stock: 59,
      rating: 4.9,
      reviewCount: 78,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Educational Puzzle 1000 Pieces`,
      brand: `Ravensburger`,
      slug: 'educational-puzzle-1000-pieces-cp0k2n',
      description: `Enjoy this high-quality Educational Puzzle 1000 Pieces from Ravensburger. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 25,
      price: 19.95,
      stock: 13,
      rating: 4.4,
      reviewCount: 42,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1500995617113-cf789362a3e1?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Plush Teddy Bear Large`,
      brand: `Gund`,
      slug: 'plush-teddy-bear-large-4oxu47',
      description: `Enjoy this high-quality Plush Teddy Bear Large from Gund. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 40,
      price: 29.5,
      stock: 25,
      rating: 4.8,
      reviewCount: 116,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Action Figure Superhero`,
      brand: `Marvel`,
      slug: 'action-figure-superhero-1ywqj7',
      description: `Enjoy this high-quality Action Figure Superhero from Marvel. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 30,
      price: 24.99,
      stock: 15,
      rating: 4.3,
      reviewCount: 40,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1608889476561-6242cfdbf622?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Board Game Strategy`,
      brand: `Catan`,
      slug: 'board-game-strategy-b5pd1l',
      description: `Enjoy this high-quality Board Game Strategy from Catan. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 55,
      price: 44,
      stock: 70,
      rating: 4.1,
      reviewCount: 109,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/71GM6UFejTL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Dollhouse with Furniture`,
      brand: `KidKraft`,
      slug: 'dollhouse-with-furniture-cxmjsk',
      description: `Enjoy this high-quality Dollhouse with Furniture from KidKraft. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 160,
      price: 120,
      stock: 103,
      rating: 4.5,
      reviewCount: 419,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/818rEgBSmtL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Science Kit for Kids`,
      brand: `Thames & Kosmos`,
      slug: 'science-kit-for-kids-ln7nao',
      description: `Enjoy this high-quality Science Kit for Kids from Thames & Kosmos. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 45,
      price: 34.99,
      stock: 108,
      rating: 4.2,
      reviewCount: 470,
      images: { create: [{ url: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Electric Train Set`,
      brand: `Lionel`,
      slug: 'electric-train-set-mr4z1',
      description: `Enjoy this high-quality Electric Train Set from Lionel. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 110,
      price: 89,
      stock: 67,
      rating: 4.8,
      reviewCount: 113,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/81na3-wy1SL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
    {
      categoryId: categoryMap['Toys'].id,
      name: `Water Gun Super Soaker`,
      brand: `Nerf`,
      slug: 'water-gun-super-soaker-sect6i',
      description: `Enjoy this high-quality Water Gun Super Soaker from Nerf. Perfect for your daily needs with excellent value and top-notch performance.`,
      mrp: 20,
      price: 15.99,
      stock: 17,
      rating: 5.0,
      reviewCount: 294,
      images: { create: [{ url: 'https://m.media-amazon.com/images/I/61MQ0r3rACL._AC_SX679_.jpg', sortOrder: 0 }] }
    },
  ];

  for (const p of products) {
    await prisma.product.create({ data: p });
  }

  console.log('Seeding complete.');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
