import { createRequire } from 'node:module';

// This bundle is generated by the Vercel build command and included explicitly
// through the function's includeFiles setting.
const require = createRequire(import.meta.url);
const app = require('../server-dist/server.cjs');

const handler = app.default || app;

export default handler;
